### ISSUE TITLE
setPictureInPictureArgs: Device doesn't support picture-in-picture mode.

### ISSUE THREAD

**Issue by qibin0506** [android/media-samples#24]
Can not run this sample on Android emulator (API O , Target Android 7+ Google API).
the exception is, 

``` java
 java.lang.IllegalStateException: setPictureInPictureArgs: Device doesn't support picture-in-picture mode.
           at android.os.Parcel.readException(Parcel.java:1923)
           at android.os.Parcel.readException(Parcel.java:1861)
           at android.app.IActivityManager$Stub$Proxy.setPictureInPictureArgs(IActivityManager.java:9378)
           at android.app.Activity.setPictureInPictureArgs(Activity.java:1984)
           at com.example.pip.MainActivity.updatePictureInPictureActions(MainActivity.java:156)
           at com.example.pip.MainActivity$2.onMovieStarted(MainActivity.java:101)
           at com.example.pip.widget.MovieView.play(MovieView.java:350)
           at com.example.pip.widget.MovieView$3.onPrepared(MovieView.java:384)
           at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:3170)
           at android.os.Handler.dispatchMessage(Handler.java:102)
           at android.os.Looper.loop(Looper.java:156)
           at android.app.ActivityThread.main(ActivityThread.java:6440)
           at java.lang.reflect.Method.invoke(Native Method)
           at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:746)
```

**Comment by mwajeeh** [comment]
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                if (getPackageManager().hasSystemFeature(PackageManager.FEATURE_PICTURE_IN_PICTURE)) {
                    if (!isInPictureInPictureMode()) {
                            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                                enterPictureInPictureMode(pipParams.build());
                            } else {
                                enterPictureInPictureMode();
                            }
                    }
                }
            }

Still getting exception on some devices `java.lang.IllegalStateException: enterPictureInPictureMode: Device doesn't support picture-in-picture mode.`

Example device:
**samsung SM-G973U1, android 10**

**Comment by peerless2012** [comment]
> @maximus9600 Picture in Picture was built into the framework until Android O. So there will be no framework support Pre-O.

Why there is PIP method like `enterPictureInPictureMode` in Android N ?
