### ISSUE TITLE
 Caused by: java.lang.RuntimeException: Fail to connect to camera service

### ISSUE THREAD

**Issue by demonsantosh** [android/media-samples#63]
Process: com.example.android.mediarecorder, PID: 8478
    java.lang.RuntimeException: An error occurred while executing doInBackground()

Caused by: java.lang.RuntimeException: Fail to connect to camera service
        at android.hardware.Camera.<init>(Camera.java:589)
        at android.hardware.Camera.open(Camera.java:439)
        at com.example.android.common.media.CameraHelper.getDefaultCameraInstance(CameraHelper.java:103)
        at com.example.android.mediarecorder.MainActivity.prepareVideoRecorder(MainActivity.java:141)
        at com.example.android.mediarecorder.MainActivity.access$000(MainActivity.java:42)
        at com.example.android.mediarecorder.MainActivity$MediaPrepareTask.doInBackground(MainActivity.java:217)
        at com.example.android.mediarecorder.MainActivity$MediaPrepareTask.doInBackground(MainActivity.java:212)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)

**Comment by ZhuSniffsTheRose** [comment]
I also meet it,   how do you solve it?
