### ISSUE TITLE
PictureInPicture - Java - Sample Application Crashes

### ISSUE THREAD

**Issue by ankurgecr** [android/media-samples#75]
The sample application crashes when checkout the repository and run the project PictureInPicture in emulator with following crash log:

```
2021-06-07 16:44:27.046 9271-9271/com.example.android.pictureinpicture E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android.pictureinpicture, PID: 9271
    java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.core.view.WindowInsetsControllerCompat.show(int)' on a null object reference
        at com.example.android.pictureinpicture.MainActivity.adjustFullScreen(MainActivity.java:313)
        at com.example.android.pictureinpicture.MainActivity.onWindowFocusChanged(MainActivity.java:241)
        at androidx.appcompat.view.WindowCallbackWrapper.onWindowFocusChanged(WindowCallbackWrapper.java:124)
        at com.android.internal.policy.DecorView.onWindowFocusChanged(DecorView.java:1701)
        at android.view.View.dispatchWindowFocusChanged(View.java:14448)
        at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1491)
        at android.view.ViewRootImpl.handleWindowFocusChanged(ViewRootImpl.java:3216)
        at android.view.ViewRootImpl.access$1100(ViewRootImpl.java:188)
        at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4999)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7464)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
2021-06-07 16:44:27.233 9271-9291/com.example.android.pictureinpicture W/MediaPlayerNative: info/warning (3, 0)
```

Tried on Emulator with `Android 11.0` and `Android 9.0`
Android Studio 4.1.3
Build #AI-201.8743.12.41.7199119, built on March 11, 2021
Runtime version: 1.8.0_242-release-1644-b3-6915495 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 4012M
Cores: 12
Registry: ide.new.welcome.screen.force=true, external.system.auto.import.disabled=true
Non-Bundled Plugins: com.intellij.marketplace, org.jetbrains.kotlin

**Comment by faith-hb** [comment]
同问，跑起来直接闪退；开发体验贼差啊
